// Write the library version into src/lib/generated/version.js so the site can
// render a single source of truth (the root package.json) in the header badge
// and hero. Runs automatically before `pnpm build` (see the `prebuild` script);
// the generated file is gitignored and regenerated on every build.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const repoRoot = resolve(root, '..');

const pkgPath = resolve(repoRoot, 'package.json');
const { version } = JSON.parse(readFileSync(pkgPath, 'utf8'));

const outDir = resolve(root, 'src/lib/generated');
const outPath = resolve(outDir, 'version.js');

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outPath,
  `// Generated by scripts/sync-version.mjs — do not edit.\nexport const version = ${JSON.stringify(version)};\n`
);
console.log(`Wrote ${outPath} (version ${version})`);
